blank_issues_enabled: false
contact_links:
  - name: ðŸ’µ AWS Billing Support
    url: https://support.aws.amazon.com/#/contacts/kiro
    about: For billing-related questions, please contact AWS Billing Support.
  - name: ðŸ’¬ Kiro Community Discord
    url: https://discord.gg/kirodotdev
    about: Join the community to discuss features, share feedback, and connect with other developers using Kiro.
  - name: ðŸ“š Kiro Documentation
    url: https://docs.kiro.dev
    about: Refer to our technical documentation for guides, best practices and troubleshooting common issues.
  - name: ðŸ‘» Kiro Website
    url: https://kiro.dev
    about: Learn about Kiro features and download the latest version.
